services:
  kafka-broker-1:
    image: confluentinc/cp-kafka:7.8.0
    container_name: kafka-broker-1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker-1:9092:9092'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-broker-1:29092'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_KRAFT_MODE: 'true'
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_LISTENER_SECURITY_PROTOCOL: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data-1:/var/lib/kafka/data
    networks:
      - kafka-net
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
        reservations:
          memory: 1G
          cpus: "0.5"

  create-topics:
    image: confluentinc/cp-kafka:7.8.0
    container_name: create-topics
    depends_on:
      - kafka-broker-1
    entrypoint: ["/bin/bash", "-c", "/create-topics.sh"]
    volumes:
      - ./create-topics.sh:/create-topics.sh
    networks:
      - kafka-net

volumes:
  kafka-data-1:

networks:
  kafka-net:
    driver: bridge
