/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BatteryFaultModel from '../model/BatteryFaultModel';

/**
* BatteryFaultController service.
* @module api/BatteryFaultControllerApi
* @version v0
*/
export default class BatteryFaultControllerApi {

    /**
    * Constructs a new BatteryFaultControllerApi. 
    * @alias module:api/BatteryFaultControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getBatteryFaults operation.
     * @callback module:api/BatteryFaultControllerApi~getBatteryFaultsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/BatteryFaultModel>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {String} [faultId] 
     * @param {String} [gps] 
     * @param {String} [vehicleId] 
     * @param {String} [batteryId] 
     * @param {String} [faultReason] 
     * @param {String} [recommendation] 
     * @param {String} [level] 
     * @param {String} [risk] 
     * @param {String} [date] 
     * @param {module:api/BatteryFaultControllerApi~getBatteryFaultsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/BatteryFaultModel>}
     */
    getBatteryFaults(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'faultId': opts['faultId'],
        'gps': opts['gps'],
        'vehicleId': opts['vehicleId'],
        'batteryId': opts['batteryId'],
        'faultReason': opts['faultReason'],
        'recommendation': opts['recommendation'],
        'level': opts['level'],
        'risk': opts['risk'],
        'date': opts['date']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [BatteryFaultModel];
      return this.apiClient.callApi(
        '/api/faults', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
