version: '3.8'

services:
  jobmanager:
    image: flink:latest
    container_name: flink_jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081" # Flink Web UI
    volumes:
      - /c/Users/User/Documents/EV/mqtt-flink/mqtt-flink/target/mqtt-flink-0.0.1-SNAPSHOT.jar:/opt/flink/usrlib/mqtt-flink-0.0.1-SNAPSHOT.jar
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager

  taskmanager:
    image: flink:latest
    container_name: flink_taskmanager
    hostname: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - /c/Users/User/Documents/EV/mqtt-flink/mqtt-flink/target/mqtt-flink-0.0.1-SNAPSHOT.jar:/opt/flink/usrlib/mqtt-flink-0.0.1-SNAPSHOT.jar
    command: taskmanager
