/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.BatteryFaultModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BatteryFaultModel', function() {
    it('should create an instance of BatteryFaultModel', function() {
      // uncomment below and update the code to test BatteryFaultModel
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be.a(OpenApiDefinition.BatteryFaultModel);
    });

    it('should have the property faultId (base name: "faultId")', function() {
      // uncomment below and update the code to test the property faultId
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

    it('should have the property gps (base name: "gps")', function() {
      // uncomment below and update the code to test the property gps
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

    it('should have the property vehicleId (base name: "vehicleId")', function() {
      // uncomment below and update the code to test the property vehicleId
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

    it('should have the property batteryId (base name: "batteryId")', function() {
      // uncomment below and update the code to test the property batteryId
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

    it('should have the property faultReason (base name: "faultReason")', function() {
      // uncomment below and update the code to test the property faultReason
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

    it('should have the property recommendation (base name: "recommendation")', function() {
      // uncomment below and update the code to test the property recommendation
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

    it('should have the property time (base name: "time")', function() {
      // uncomment below and update the code to test the property time
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

    it('should have the property level (base name: "level")', function() {
      // uncomment below and update the code to test the property level
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

    it('should have the property risk (base name: "risk")', function() {
      // uncomment below and update the code to test the property risk
      //var instance = new OpenApiDefinition.BatteryFaultModel();
      //expect(instance).to.be();
    });

  });

}));
