version: '3.8'
services:
  influxdb:
    image: influxdb:2.7.11
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - influxv2.env	
    volumes:
      - influxdb-data:/var/lib/influxdb2:rw	
volumes:
  influxdb-data:
