version: '3.8'

services:
  app:
    image: reporting-api:latest
    build:
      context: .ReportingAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my-postgres:5432/battery_inventory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Postgres2025
    networks:
      - postgress_my_network

networks:
  postgress_my_network:
    external: true
