version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - "1883:1883"  # MQTT default port
      - "9001:9001"  # WebSocket port (optional)
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
