/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BatteryFaultModel model module.
 * @module model/BatteryFaultModel
 * @version v0
 */
class BatteryFaultModel {
    /**
     * Constructs a new <code>BatteryFaultModel</code>.
     * @alias module:model/BatteryFaultModel
     * @param gps {String} 
     * @param vehicleId {String} 
     * @param batteryId {String} 
     * @param faultReason {String} 
     * @param recommendation {String} 
     * @param time {Date} 
     * @param level {String} 
     * @param risk {String} 
     */
    constructor(gps, vehicleId, batteryId, faultReason, recommendation, time, level, risk) { 
        
        BatteryFaultModel.initialize(this, gps, vehicleId, batteryId, faultReason, recommendation, time, level, risk);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, gps, vehicleId, batteryId, faultReason, recommendation, time, level, risk) { 
        obj['gps'] = gps;
        obj['vehicleId'] = vehicleId;
        obj['batteryId'] = batteryId;
        obj['faultReason'] = faultReason;
        obj['recommendation'] = recommendation;
        obj['time'] = time;
        obj['level'] = level;
        obj['risk'] = risk;
    }

    /**
     * Constructs a <code>BatteryFaultModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BatteryFaultModel} obj Optional instance to populate.
     * @return {module:model/BatteryFaultModel} The populated <code>BatteryFaultModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BatteryFaultModel();

            if (data.hasOwnProperty('faultId')) {
                obj['faultId'] = ApiClient.convertToType(data['faultId'], 'String');
            }
            if (data.hasOwnProperty('gps')) {
                obj['gps'] = ApiClient.convertToType(data['gps'], 'String');
            }
            if (data.hasOwnProperty('vehicleId')) {
                obj['vehicleId'] = ApiClient.convertToType(data['vehicleId'], 'String');
            }
            if (data.hasOwnProperty('batteryId')) {
                obj['batteryId'] = ApiClient.convertToType(data['batteryId'], 'String');
            }
            if (data.hasOwnProperty('faultReason')) {
                obj['faultReason'] = ApiClient.convertToType(data['faultReason'], 'String');
            }
            if (data.hasOwnProperty('recommendation')) {
                obj['recommendation'] = ApiClient.convertToType(data['recommendation'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'Date');
            }
            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'String');
            }
            if (data.hasOwnProperty('risk')) {
                obj['risk'] = ApiClient.convertToType(data['risk'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BatteryFaultModel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BatteryFaultModel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BatteryFaultModel.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['faultId'] && !(typeof data['faultId'] === 'string' || data['faultId'] instanceof String)) {
            throw new Error("Expected the field `faultId` to be a primitive type in the JSON string but got " + data['faultId']);
        }
        // ensure the json data is a string
        if (data['gps'] && !(typeof data['gps'] === 'string' || data['gps'] instanceof String)) {
            throw new Error("Expected the field `gps` to be a primitive type in the JSON string but got " + data['gps']);
        }
        // ensure the json data is a string
        if (data['vehicleId'] && !(typeof data['vehicleId'] === 'string' || data['vehicleId'] instanceof String)) {
            throw new Error("Expected the field `vehicleId` to be a primitive type in the JSON string but got " + data['vehicleId']);
        }
        // ensure the json data is a string
        if (data['batteryId'] && !(typeof data['batteryId'] === 'string' || data['batteryId'] instanceof String)) {
            throw new Error("Expected the field `batteryId` to be a primitive type in the JSON string but got " + data['batteryId']);
        }
        // ensure the json data is a string
        if (data['faultReason'] && !(typeof data['faultReason'] === 'string' || data['faultReason'] instanceof String)) {
            throw new Error("Expected the field `faultReason` to be a primitive type in the JSON string but got " + data['faultReason']);
        }
        // ensure the json data is a string
        if (data['recommendation'] && !(typeof data['recommendation'] === 'string' || data['recommendation'] instanceof String)) {
            throw new Error("Expected the field `recommendation` to be a primitive type in the JSON string but got " + data['recommendation']);
        }
        // ensure the json data is a string
        if (data['level'] && !(typeof data['level'] === 'string' || data['level'] instanceof String)) {
            throw new Error("Expected the field `level` to be a primitive type in the JSON string but got " + data['level']);
        }
        // ensure the json data is a string
        if (data['risk'] && !(typeof data['risk'] === 'string' || data['risk'] instanceof String)) {
            throw new Error("Expected the field `risk` to be a primitive type in the JSON string but got " + data['risk']);
        }

        return true;
    }


}

BatteryFaultModel.RequiredProperties = ["gps", "vehicleId", "batteryId", "faultReason", "recommendation", "time", "level", "risk"];

/**
 * @member {String} faultId
 */
BatteryFaultModel.prototype['faultId'] = undefined;

/**
 * @member {String} gps
 */
BatteryFaultModel.prototype['gps'] = undefined;

/**
 * @member {String} vehicleId
 */
BatteryFaultModel.prototype['vehicleId'] = undefined;

/**
 * @member {String} batteryId
 */
BatteryFaultModel.prototype['batteryId'] = undefined;

/**
 * @member {String} faultReason
 */
BatteryFaultModel.prototype['faultReason'] = undefined;

/**
 * @member {String} recommendation
 */
BatteryFaultModel.prototype['recommendation'] = undefined;

/**
 * @member {Date} time
 */
BatteryFaultModel.prototype['time'] = undefined;

/**
 * @member {String} level
 */
BatteryFaultModel.prototype['level'] = undefined;

/**
 * @member {String} risk
 */
BatteryFaultModel.prototype['risk'] = undefined;






export default BatteryFaultModel;

